export const fixtureData = {
  'ChIJ4RQESkRZwokRzOSbHg_AHd8': {
    "id": "ChIJ4RQESkRZwokRzOSbHg_AHd8",
    "name": "Mr. Plum",
    "address": "658 Manhattan Ave, Brooklyn, NY 11222, USA",
    "types": [
      "grocery_or_supermarket",
      "food",
      "point_of_interest",
      "store",
      "establishment"
    ],
    "coordinates": {
      "lat": 40.72458830000001,
      "lng": -73.9510168
    },
    "rating": 4.5,
    "rating_n": 39,
    "international_phone_number": "+1 718-349-2321",
    "populartimes": [
      {
        "name": "Monday",
        "data": [
          4,
          4,
          0,
          4,
          4,
          4,
          4,
          17,
          30,
          47,
          65,
          73,
          73,
          65,
          56,
          60,
          78,
          95,
          100,
          78,
          47,
          21,
          4,
          4
        ]
      },
      {
        "name": "Tuesday",
        "data": [
          0,
          4,
          4,
          4,
          4,
          4,
          8,
          13,
          21,
          30,
          39,
          43,
          47,
          43,
          39,
          39,
          47,
          69,
          78,
          56,
          21,
          4,
          4,
          4
        ]
      },
      {
        "name": "Wednesday",
        "data": [
          4,
          4,
          4,
          4,
          4,
          0,
          4,
          17,
          47,
          52,
          56,
          65,
          60,
          56,
          52,
          47,
          52,
          56,
          56,
          52,
          43,
          34,
          21,
          13
        ]
      },
      {
        "name": "Thursday",
        "data": [
          4,
          4,
          4,
          4,
          4,
          4,
          4,
          4,
          8,
          26,
          52,
          69,
          69,
          56,
          43,
          34,
          39,
          43,
          43,
          39,
          26,
          13,
          4,
          4
        ]
      },
      {
        "name": "Friday",
        "data": [
          4,
          4,
          4,
          4,
          4,
          4,
          8,
          21,
          34,
          56,
          73,
          86,
          91,
          91,
          82,
          78,
          73,
          73,
          69,
          60,
          47,
          30,
          17,
          8
        ]
      },
      {
        "name": "Saturday",
        "data": [
          4,
          4,
          4,
          4,
          4,
          4,
          0,
          4,
          8,
          26,
          52,
          65,
          65,
          56,
          47,
          43,
          43,
          43,
          39,
          34,
          30,
          21,
          13,
          8
        ]
      },
      {
        "name": "Sunday",
        "data": [
          4,
          4,
          4,
          4,
          4,
          4,
          4,
          0,
          4,
          13,
          39,
          69,
          82,
          73,
          56,
          47,
          52,
          60,
          69,
          65,
          52,
          34,
          17,
          4
        ]
      }
    ],
    "time_wait": [
      {
        "name": "Monday",
        "data": [
          5,
          5,
          5,
          5,
          0,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5
        ]
      },
      {
        "name": "Tuesday",
        "data": [
          5,
          5,
          5,
          5,
          0,
          0,
          0,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          0
        ]
      },
      {
        "name": "Wednesday",
        "data": [
          0,
          5,
          5,
          0,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5
        ]
      },
      {
        "name": "Thursday",
        "data": [
          0,
          0,
          0,
          0,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5
        ]
      },
      {
        "name": "Friday",
        "data": [
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5
        ]
      },
      {
        "name": "Saturday",
        "data": [
          5,
          5,
          5,
          5,
          0,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5
        ]
      },
      {
        "name": "Sunday",
        "data": [
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5
        ]
      }
    ],
    "time_spent": [
      15,
      15
    ]
  },
  'ChIJ-VYyzkZZwokRLaDlVih5Qzs': {
    "id": "ChIJ-VYyzkZZwokRLaDlVih5Qzs",
    "name": "Associated Supermarkets",
    "address": "802 Manhattan Ave, Brooklyn, NY 11222, USA",
    "types": [
      "supermarket",
      "convenience_store",
      "grocery_or_supermarket",
      "food",
      "point_of_interest",
      "store",
      "establishment"
    ],
    "coordinates": {
      "lat": 40.7280239,
      "lng": -73.9529007
    },
    "rating": 3.8,
    "rating_n": 127,
    "international_phone_number": "+1 718-383-7756",
    "populartimes": [
      {
        "name": "Monday",
        "data": [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          15,
          28,
          39,
          45,
          53,
          60,
          60,
          51,
          52,
          69,
          65,
          31,
          0,
          0,
          0,
          0
        ]
      },
      {
        "name": "Tuesday",
        "data": [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          15,
          29,
          42,
          52,
          57,
          56,
          50,
          52,
          68,
          76,
          51,
          20,
          0,
          0,
          0,
          0
        ]
      },
      {
        "name": "Wednesday",
        "data": [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          9,
          14,
          23,
          36,
          44,
          45,
          43,
          45,
          54,
          57,
          48,
          29,
          0,
          0,
          0,
          0
        ]
      },
      {
        "name": "Thursday",
        "data": [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          16,
          25,
          31,
          36,
          44,
          52,
          54,
          46,
          35,
          52,
          90,
          42,
          0,
          0,
          0,
          0
        ]
      },
      {
        "name": "Friday",
        "data": [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          20,
          31,
          36,
          36,
          48,
          66,
          56,
          34,
          41,
          71,
          76,
          47,
          0,
          0,
          0,
          0
        ]
      },
      {
        "name": "Saturday",
        "data": [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          23,
          42,
          56,
          69,
          89,
          100,
          90,
          75,
          68,
          61,
          45,
          25,
          0,
          0,
          0,
          0
        ]
      },
      {
        "name": "Sunday",
        "data": [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          20,
          43,
          65,
          73,
          68,
          67,
          66,
          48,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ]
      }
    ],
    "time_wait": [
      {
        "name": "Monday",
        "data": [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          0,
          0,
          0,
          0
        ]
      },
      {
        "name": "Tuesday",
        "data": [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          0,
          0,
          0,
          0
        ]
      },
      {
        "name": "Wednesday",
        "data": [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          0,
          0,
          0,
          0
        ]
      },
      {
        "name": "Thursday",
        "data": [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          0,
          0,
          0,
          0
        ]
      },
      {
        "name": "Friday",
        "data": [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          0,
          0,
          0,
          0
        ]
      },
      {
        "name": "Saturday",
        "data": [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          0,
          0,
          0,
          0
        ]
      },
      {
        "name": "Sunday",
        "data": [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ]
      }
    ],
    "time_spent": [
      20,
      20
    ]
  },
  'ChIJGfDg705ZwokRvqa_3iQAPsQ': {
    "id": "ChIJGfDg705ZwokRvqa_3iQAPsQ",
    "name": "Met Foodmarkets",
    "address": "131 Driggs Ave, Brooklyn, NY 11222, USA",
    "types": [
      "supermarket",
      "grocery_or_supermarket",
      "food",
      "point_of_interest",
      "store",
      "establishment"
    ],
    "coordinates": {
      "lat": 40.72288880000001,
      "lng": -73.9437891
    },
    "rating": 4.0,
    "rating_n": 198,
    "international_phone_number": "+1 718-389-6429",
    "populartimes": [
      {
        "name": "Monday",
        "data": [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          12,
          24,
          34,
          34,
          31,
          30,
          32,
          34,
          42,
          58,
          74,
          73,
          51,
          24,
          0,
          0,
          0
        ]
      },
      {
        "name": "Tuesday",
        "data": [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          9,
          38,
          32,
          15,
          22,
          36,
          46,
          48,
          47,
          55,
          71,
          74,
          50,
          21,
          0,
          0,
          0
        ]
      },
      {
        "name": "Wednesday",
        "data": [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          6,
          14,
          20,
          22,
          23,
          28,
          35,
          38,
          34,
          34,
          53,
          66,
          42,
          12,
          0,
          0,
          0
        ]
      },
      {
        "name": "Thursday",
        "data": [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          5,
          18,
          27,
          23,
          25,
          35,
          41,
          38,
          34,
          39,
          50,
          53,
          41,
          22,
          0,
          0,
          0
        ]
      },
      {
        "name": "Friday",
        "data": [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          12,
          22,
          29,
          31,
          32,
          37,
          41,
          37,
          29,
          35,
          56,
          61,
          38,
          12,
          0,
          0,
          0
        ]
      },
      {
        "name": "Saturday",
        "data": [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          11,
          27,
          35,
          32,
          37,
          53,
          62,
          61,
          59,
          65,
          70,
          62,
          41,
          20,
          0,
          0,
          0
        ]
      },
      {
        "name": "Sunday",
        "data": [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          9,
          18,
          30,
          44,
          56,
          62,
          60,
          52,
          55,
          100,
          83,
          20,
          0,
          0,
          0,
          0,
          0
        ]
      }
    ],
    "time_wait": [
      {
        "name": "Monday",
        "data": [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          0,
          0,
          0
        ]
      },
      {
        "name": "Tuesday",
        "data": [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          0,
          0,
          0
        ]
      },
      {
        "name": "Wednesday",
        "data": [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          0,
          0,
          0
        ]
      },
      {
        "name": "Thursday",
        "data": [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          0,
          0,
          0
        ]
      },
      {
        "name": "Friday",
        "data": [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          0,
          0,
          0
        ]
      },
      {
        "name": "Saturday",
        "data": [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          0,
          0,
          0
        ]
      },
      {
        "name": "Sunday",
        "data": [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          5,
          0,
          0,
          0,
          0,
          0
        ]
      }
    ],
    "time_spent": [
      15,
      15
    ]
  },
  'ChIJ_2Ukz0ZZwokRJZSgVQYl2eo': {
    "id": "ChIJ_2Ukz0ZZwokRJZSgVQYl2eo",
    "name": "Chase Bank",
    "address": "798 Manhattan Ave, Brooklyn, NY 11222, USA",
    "types": [
      "bank",
      "atm",
      "finance",
      "point_of_interest",
      "establishment"
    ],
    "coordinates": {
      "lat": 40.7278683,
      "lng": -73.9528005
    },
    "rating": 3.2,
    "rating_n": 32,
    "international_phone_number": "+1 718-392-6106",
    "populartimes": [
      {
        "name": "Monday",
        "data": [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          32,
          45,
          56,
          65,
          68,
          64,
          55,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ]
      },
      {
        "name": "Tuesday",
        "data": [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          32,
          50,
          64,
          69,
          64,
          60,
          76,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ]
      },
      {
        "name": "Wednesday",
        "data": [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          24,
          35,
          43,
          50,
          58,
          65,
          66,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ]
      },
      {
        "name": "Thursday",
        "data": [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          26,
          40,
          55,
          69,
          76,
          76,
          67,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ]
      },
      {
        "name": "Friday",
        "data": [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          40,
          59,
          69,
          71,
          76,
          89,
          100,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ]
      },
      {
        "name": "Saturday",
        "data": [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          35,
          64,
          81,
          70,
          45,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ]
      },
      {
        "name": "Sunday",
        "data": [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ]
      }
    ],
    "time_spent": [
      15,
      15
    ]
  }
};